### ISSUE TITLE
Insert on web client's "Absenden" fails

### ISSUE THREAD

**Issue by SimonMilan** [fgreinus/jwebpoll#2]
```
[qtp1516663366-22] ERROR spark.webserver.MatcherFilter - 
java.sql.SQLException: Unable to run insert stmt on object de.lebk.jwebpoll.data.Vote@7b49d45d:
INSERT INTO `votes` (`id` ,`session` ,`created` ,`question_id` ,`answer_id` ,`userText` ) VALUES (?,?,?,?,?,?)
    at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
    at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
    at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
    at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
    at de.lebk.jwebpoll.Frontend.lambda$bindSparkRoutes$25(Frontend.java:139)
    at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66)
...
```

**Comment by SimonMilan** [comment]
Fixed.
